insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (1, 'Wholesale');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (2, 'Retail');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (3, 'Marketplace');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (4, 'Catalog');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (5, 'Distributor');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (6, 'Reseller');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (7, 'Internet');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (8, 'Indirect');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (9, 'B2B');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (10, 'Manufacturer');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (11, 'Direct sales');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (12, 'White label');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (13, 'Hybrid');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (14, 'Partnership');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (15, 'Ecommerce');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (16, 'Brokers');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (17, 'Search engine optimization');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (18, 'Social media');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (19, 'Distribution');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (20, 'Affiliate sales');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (21, 'Mobile apps');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (22, 'Consultant');
insert into put_channel_type (put_channel_type_id, put_channel_type_description) values (23, 'Indirect');
