insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (1, 'Global Express', 'Fast Express Shipping');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (2, 'Ocean Freight Co.', 'Swift Delivery Services');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (3, 'Air Cargo Express', 'Reliable Freight Co.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (4, 'Swift Shipping', 'Speedy Shipments Inc.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (5, 'Worldwide Logistics', 'Quick Cargo Transport');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (6, 'International Movers Inc.', 'Fast Express Shipping');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (7, 'Global Transport Solutions', 'Swift Delivery Services');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (8, 'Universal Shipping Co.', 'Reliable Freight Co.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (9, 'Global Courier Services', 'Speedy Shipments Inc.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (10, 'International Parcel Express', 'Quick Cargo Transport');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (11, 'Brasil Express', 'Fast Express Shipping');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (12, 'Amazonia Shipping', 'Swift Delivery Services');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (13, 'Samba Logistics', 'Reliable Freight Co.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (14, 'Carioca Couriers', 'Speedy Shipments Inc.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (15, 'Pantanal Parcel', 'Quick Cargo Transport');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (16, 'SEDEX', 'Fast Express Shipping');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (17, 'TNT', 'Swift Delivery Services');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (18, 'EuroExpress', 'Reliable Freight Co.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (19, 'SwiftShip', 'Speedy Shipments Inc.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (20, 'BlueCargo', 'Quick Cargo Transport');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (21, 'FastTrack', 'Fast Express Shipping');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (22, 'EuroLine', 'Swift Delivery Services');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (23, 'SpeedyDeliver', 'Reliable Freight Co.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (24, 'GlobalConnect', 'Speedy Shipments Inc.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (25, 'RapidTransit', 'Quick Cargo Transport');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (26, 'EuroShip', 'Fast Express Shipping');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (27, 'QuickHaul', 'Swift Delivery Services');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (28, 'Zenith Shipping Co.', 'Reliable Freight Co.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (29, 'Dragon Express', 'Speedy Shipments Inc.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (30, 'Lotus Logistics', 'Quick Cargo Transport');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (31, 'Golden Crane Shipping', 'Fast Express Shipping');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (32, 'Silk Road Carriers', 'Swift Delivery Services');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (33, 'Jade Star Shipping', 'Reliable Freight Co.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (34, 'Eastern Pearl Logistics', 'Speedy Shipments Inc.');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (35, 'Sunrise Shipping Services', 'Quick Cargo Transport');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (36, 'Bamboo Express', 'Fast Express Shipping');
insert into distribution_channel (distribution_channel_id, distribution_channel_name, distribution_channel_description) values (37, 'Cherry Blossom Transport', 'Swift Delivery Services');