insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (1, 14, 'Visa');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (2, 5, 'Mastercard');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (3, 5, 'American Express');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (4, 6, 'Sorocred');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (5, 19, 'Diners Club');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (6, 17, 'How much');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (7, 2, 'Hipercard');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (8, 14, 'Aura');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (9, 3, 'Cabal');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (10, 8, 'Allele');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (11, 19, 'Banes Card');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (12, 12, 'CalCard');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (13, 19, 'Credz');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (14, 9, 'Discover');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (15, 17, 'GoodCard');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (16, 15, 'GreenCard');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (17, 8, 'Hyper');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (18, 17, 'JcB');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (19, 10, 'More');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (20, 10, 'MaxVan');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (21, 14, 'Policard');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (22, 12, 'RedeCompras');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (23, 8, 'Sodexo');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (24, 6, 'ValeCard');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (25, 6, 'Verocheque');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (26, 12, 'VR');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (27, 12, 'Ticket');
insert into payment_provider (payment_provider_id, payment_provider_type_id, payment_provider_name) values (28, 15, 'Others');
