insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (1, 'Amazon', 3);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (2, 'eBay', 13);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (3, 'Alibaba', 13);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (4, 'Walmart', 3);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (5, 'Etsy', 20);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (6, 'Target', 3);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (7, 'Flipkart', 23);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (8, 'Rakuten', 16);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (9, 'Zalando', 21);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (10, 'JD.com', 20);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (11, 'Shopify', 9);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (12, 'ASOS', 16);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (13, 'Best Buy', 22);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (14, 'Taobao', 4);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (15, 'Wayfair', 21);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (16, 'Qoo10', 2);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (17, 'Lazada', 19);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (18, 'Groupon', 18);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (19, 'Overstock Shopify', 12);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (20, 'Etsy', 20);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (21, 'Walmart', 15);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (22, 'eBay', 3);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (23, 'Target Wholesale', 2);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (24, 'Best Buy', 5);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (25, 'Wayfair', 3);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (26, 'Newegg', 18);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (27, 'MercadoLibre', 7);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (28, 'Linio', 8);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (29, 'Dafiti', 6);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (30, 'Rappi', 15);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (31, 'Cornershop', 9);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (32, 'Netshoes', 16);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (33, 'Falabella', 7);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (34, 'Cencosud', 20);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (35, 'TiendaMIA', 18);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (36, 'Amazon Europe', 17);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (37, 'eBay Europe', 13);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (38, 'Zalando', 22);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (39, 'Alibaba Europe', 13);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (40, 'Otto Group', 20);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (41, 'ASOS Europe', 9);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (42, 'Cdiscount', 4);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (43, 'Rakuten Europe', 18);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (44, 'Fnac Europe', 16);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (45, 'Vente-privee', 20);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (46, 'Amazon Asia', 14);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (47, 'eBay Asia', 20);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (48, 'Alibaba Asia', 7);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (49, 'Shopee Asia', 11);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (50, 'Lazada Asia', 1);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (51, 'Tokopedia Asia', 14);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (52, 'Rakuten Asia', 11);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (53, 'JD.com Asia', 13);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (54, 'Flipkart Asia', 20);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (55, 'Zalora Asia', 4);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (56, 'OceanBay', 8);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (57, 'AquaMarket', 5);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (58, 'WaveShop', 11);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (59, 'CoralMart', 5);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (60, 'PacificPlaza', 6);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (61, 'IslandBazaar', 10);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (62, 'SeashellStore', 1);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (63, 'TideTrade', 22);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (64, 'ReefRetail', 16);
insert into order_put_channel (order_put_channel_id, order_put_channel_name, put_channel_type_id) values (65, 'SurfShop', 3);
