insert into payment_type (payment_type_id, payment_type_description) values (1, 'Money');
insert into payment_type (payment_type_id, payment_type_description) values (2, 'Bank check');
insert into payment_type (payment_type_id, payment_type_description) values (3, 'Credit card');
insert into payment_type (payment_type_id, payment_type_description) values (4, 'Debit card');
insert into payment_type (payment_type_id, payment_type_description) values (5, 'Store Credit');
insert into payment_type (payment_type_id, payment_type_description) values (6, 'Food Voucher');
insert into payment_type (payment_type_id, payment_type_description) values (7, 'Meal ticket');
insert into payment_type (payment_type_id, payment_type_description) values (8, 'Gift voucher');
insert into payment_type (payment_type_id, payment_type_description) values (9, 'Fuel Voucher');
insert into payment_type (payment_type_id, payment_type_description) values (10, 'Commercial Duplicate');
insert into payment_type (payment_type_id, payment_type_description) values (11, 'Bank slip');
insert into payment_type (payment_type_id, payment_type_description) values (12, 'Bank deposit');
insert into payment_type (payment_type_id, payment_type_description) values (13, 'Instant Payment');
insert into payment_type (payment_type_id, payment_type_description) values (14, 'Bank transfer');
insert into payment_type (payment_type_id, payment_type_description) values (15, 'Digital Wallet');
insert into payment_type (payment_type_id, payment_type_description) values (16, 'Loyalty program');
insert into payment_type (payment_type_id, payment_type_description) values (17, 'Cashback');
insert into payment_type (payment_type_id, payment_type_description) values (18, 'Virtual Credit');
insert into payment_type (payment_type_id, payment_type_description) values (19, 'other');
