insert into product_category (category_id, name, description) values (1, 'Electronics', 'electronics');
insert into product_category (category_id, name, description) values (2, 'Clothing', 'clothing');
insert into product_category (category_id, name, description) values (3, 'Home Decor', 'home goods');
insert into product_category (category_id, name, description) values (4, 'Outdoor Gear', 'sports equipment');
insert into product_category (category_id, name, description) values (5, 'Beauty', 'toys');
insert into product_category (category_id, name, description) values (6, 'Toys', 'kitchen appliances');
insert into product_category (category_id, name, description) values (7, 'Sports Equipment', 'beauty products');
insert into product_category (category_id, name, description) values (8, 'Books', 'pet supplies');
insert into product_category (category_id, name, description) values (9, 'Kitchen Appliances', 'office supplies');
insert into product_category (category_id, name, description) values (10, 'Pet Supplies', 'outdoor gear');
insert into product_category (category_id, name, description) values (11, 'Jewelry', 'electronics');
insert into product_category (category_id, name, description) values (12, 'Furniture', 'clothing');
insert into product_category (category_id, name, description) values (13, 'Health and Wellness', 'home goods');
insert into product_category (category_id, name, description) values (14, 'Automotive', 'sports equipment');
insert into product_category (category_id, name, description) values (15, 'Gardening Supplies', 'toys');
insert into product_category (category_id, name, description) values (16, 'Art Supplies', 'kitchen appliances');
insert into product_category (category_id, name, description) values (17, 'Office Supplies', 'beauty products');
insert into product_category (category_id, name, description) values (18, 'Baby Products', 'pet supplies');
insert into product_category (category_id, name, description) values (19, 'Fitness Equipment', 'office supplies');
insert into product_category (category_id, name, description) values (20, 'Travel Accessories', 'outdoor gear');
insert into product_category (category_id, name, description) values (21, 'Craft Supplies', 'electronics');
insert into product_category (category_id, name, description) values (22, 'Party Supplies', 'clothing');
insert into product_category (category_id, name, description) values (23, 'Tech Gadgets', 'home goods');
insert into product_category (category_id, name, description) values (24, 'Musical Instruments', 'sports equipment');
insert into product_category (category_id, name, description) values (25, 'Food and Beverages', 'toys');
insert into product_category (category_id, name, description) values (26, 'Stationery', 'kitchen appliances');
insert into product_category (category_id, name, description) values (27, 'DIY Tools', 'beauty products');
insert into product_category (category_id, name, description) values (28, 'Video Games', 'pet supplies');
insert into product_category (category_id, name, description) values (29, 'Hobbies', 'office supplies');
insert into product_category (category_id, name, description) values (30, 'Home Improvement', 'outdoor gear');
insert into product_category (category_id, name, description) values (31, 'Personal Care', 'electronics');
insert into product_category (category_id, name, description) values (32, 'Educational Toys', 'clothing');
insert into product_category (category_id, name, description) values (33, 'Fashion Accessories', 'home goods');
insert into product_category (category_id, name, description) values (34, 'Cookware', 'sports equipment');
insert into product_category (category_id, name, description) values (35, 'Cleaning Supplies', 'toys');
insert into product_category (category_id, name, description) values (36, 'Gifts', 'kitchen appliances');
insert into product_category (category_id, name, description) values (37, 'Outdoor Furniture', 'beauty products');
insert into product_category (category_id, name, description) values (38, 'Fitness Apparel', 'pet supplies');
insert into product_category (category_id, name, description) values (39, 'Gourmet Foods', 'office supplies');
insert into product_category (category_id, name, description) values (40, 'Pet Accessories', 'outdoor gear');
insert into product_category (category_id, name, description) values (41, 'Board Games', 'electronics');
insert into product_category (category_id, name, description) values (42, 'Camping Gear', 'clothing');
insert into product_category (category_id, name, description) values (43, 'Smart Home Devices', 'home goods');
insert into product_category (category_id, name, description) values (44, 'Baby Gear', 'sports equipment');
insert into product_category (category_id, name, description) values (45, 'Skincare', 'toys');
insert into product_category (category_id, name, description) values (46, 'Handmade Crafts', 'kitchen appliances');
insert into product_category (category_id, name, description) values (47, 'Vintage Items', 'beauty products');
insert into product_category (category_id, name, description) values (48, 'Collectibles', 'pet supplies');
insert into product_category (category_id, name, description) values (49, 'Electronics', 'office supplies');
insert into product_category (category_id, name, description) values (50, 'Clothing', 'outdoor gear');
