LoadTableCustomer.sql
LoadTableCustomerAddress.sql
LoadTablePaymentType.sql
LoadTablePaymentProvider.sql
LoadTableCustomerPayment.sql
LoadTablePutChannelType.sql
popula_transacional_tabela_order_put_channel.sql
LoadTablePutChannel.sql
LoadTableDistributionChannel.sql
LoadTableSupplier.sql
LoadTableSupplierAddress.sql
LoadTableProductCategory.sql
LoadTableProduct.sql
LoadTableShoppingSession.sql
LoadTableCartItem.sql
LoadTableOrderDetails.sql
LoadTableOrderItems.sql
LoadTablePaymentDetails.sql